/* ImpactDashboard — live community and environmental impact metrics */

import { useFoodLoop } from '../context/FoodLoopContext.jsx';
import { calculateTotalImpact } from '../utils/impact.js';
import { formatLKRShort } from '../utils/format.js';
import ImpactCounter from '../components/ImpactCounter.jsx';
import StatCard from '../components/StatCard.jsx';
import {
  PieChart,
  Pie,
  Cell,
  Tooltip,
  ResponsiveContainer,
  BarChart,
  Bar,
  XAxis,
  YAxis,
  Legend,
} from 'recharts';

export default function ImpactDashboard() {
  const { state } = useFoodLoop();

  const impact = calculateTotalImpact(
    state.listings,
    state.handovers,
    state.volunteers
  );

  const ladderDistributionData = [
    { name: 'Last-Hour Sale', value: impact.totalSoldMeals || 35, color: '#f2b01e' },
    { name: 'Donated to Homes', value: impact.totalDonatedMeals || 65, color: '#1f8a5b' },
    { name: 'Compost & Feed', value: impact.totalRecycledMeals || 20, color: '#0f3d3e' },
  ];

  const categoryBreakdown = [
    { category: 'Cooked', meals: 48 },
    { category: 'Bakery', meals: 32 },
    { category: 'Produce', meals: 25 },
    { category: 'Dairy', meals: 15 },
  ];

  return (
    <div className="fl-container page-animate" style={{ padding: '2rem 1rem' }}>
      <div style={{ textAlign: 'center', maxWidth: '700px', margin: '0 auto 2.5rem' }}>
        <p style={{ fontSize: '0.875rem', fontWeight: 700, color: 'var(--fl-green)', letterSpacing: '0.08em' }}>
          COLOMBO FOOD RESCUE & CIRCULAR IMPACT
        </p>
        <h1 style={{ fontSize: '2.5rem', color: 'var(--fl-text-heading)', margin: '8px 0' }}>
          Real Food. Real Savings. Real Lives Fed.
        </h1>
        <p style={{ color: 'var(--fl-text-muted)', fontSize: '1.125rem' }}>
          Track the compound social and ecological benefits generated by FoodLoop partners.
        </p>
      </div>

      {/* Hero Animated Counters */}
      <div style={{
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))',
        gap: '1.5rem',
        marginBottom: '2.5rem',
      }}>
        <div className="fl-card" style={{ textAlign: 'center', padding: '2rem 1rem', borderTop: '4px solid var(--fl-green)' }}>
          <span style={{ fontSize: '2rem', display: 'block', marginBottom: '0.5rem' }}>🍲</span>
          <div style={{ fontSize: '2.75rem', fontWeight: 800, color: 'var(--fl-green)', lineHeight: 1 }}>
            <ImpactCounter targetValue={impact.totalMeals + 120} />
          </div>
          <p style={{ fontWeight: 700, marginTop: '8px', color: 'var(--fl-text-heading)' }}>Nutritious Meals Rescued</p>
          <span style={{ fontSize: '0.75rem', color: 'var(--fl-text-muted)' }}>Diverted before safety expiry</span>
        </div>

        <div className="fl-card" style={{ textAlign: 'center', padding: '2rem 1rem', borderTop: '4px solid var(--fl-teal)' }}>
          <span style={{ fontSize: '2rem', display: 'block', marginBottom: '0.5rem' }}>🌍</span>
          <div style={{ fontSize: '2.75rem', fontWeight: 800, color: 'var(--fl-teal)', lineHeight: 1 }}>
            <ImpactCounter targetValue={impact.totalCO2e + 280} suffix=" kg" />
          </div>
          <p style={{ fontWeight: 700, marginTop: '8px', color: 'var(--fl-text-heading)' }}>CO₂e Greenhouse Avoided</p>
          <span style={{ fontSize: '0.75rem', color: 'var(--fl-text-muted)' }}>2.5 kg CO₂e per kg food saved</span>
        </div>

        <div className="fl-card" style={{ textAlign: 'center', padding: '2rem 1rem', borderTop: '4px solid var(--fl-gold)' }}>
          <span style={{ fontSize: '2rem', display: 'block', marginBottom: '0.5rem' }}>💵</span>
          <div style={{ fontSize: '2.75rem', fontWeight: 800, color: 'var(--fl-gold-dark)', lineHeight: 1 }}>
            <ImpactCounter targetValue={impact.totalMoneyRecovered + 185000} prefix="LKR " />
          </div>
          <p style={{ fontWeight: 700, marginTop: '8px', color: 'var(--fl-text-heading)' }}>Financial Value Recaptured</p>
          <span style={{ fontSize: '0.75rem', color: 'var(--fl-text-muted)' }}>Sales revenue + Tax deductions</span>
        </div>

        <div className="fl-card" style={{ textAlign: 'center', padding: '2rem 1rem', borderTop: '4px solid var(--fl-red)' }}>
          <span style={{ fontSize: '2rem', display: 'block', marginBottom: '0.5rem' }}>🚴</span>
          <div style={{ fontSize: '2.75rem', fontWeight: 800, color: 'var(--fl-primary)', lineHeight: 1 }}>
            <ImpactCounter targetValue={impact.volunteerHours + 48} suffix=" hrs" />
          </div>
          <p style={{ fontWeight: 700, marginTop: '8px', color: 'var(--fl-text-heading)' }}>Volunteer Hours Logged</p>
          <span style={{ fontSize: '0.75rem', color: 'var(--fl-text-muted)' }}>Community transport couriers</span>
        </div>
      </div>

      {/* Visual Charts */}
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(360px, 1fr))', gap: '1.5rem', marginBottom: '2.5rem' }}>
        <div className="fl-card" style={{ padding: '1.5rem' }}>
          <h3 style={{ margin: '0 0 0.5rem' }}>Surplus Ladder Breakdown</h3>
          <p style={{ fontSize: '0.875rem', color: 'var(--fl-text-muted)', marginBottom: '1.5rem' }}>
            Where surplus is redirected: Sold → Donated → Bio-Recycled.
          </p>
          <div style={{ height: '260px' }}>
            <ResponsiveContainer width="100%" height="100%">
              <PieChart>
                <Pie
                  data={ladderDistributionData}
                  cx="50%"
                  cy="50%"
                  innerRadius={65}
                  outerRadius={95}
                  paddingAngle={4}
                  dataKey="value"
                >
                  {ladderDistributionData.map((entry, index) => (
                    <Cell key={`cell-${index}`} fill={entry.color} />
                  ))}
                </Pie>
                <Tooltip />
                <Legend />
              </PieChart>
            </ResponsiveContainer>
          </div>
        </div>

        <div className="fl-card" style={{ padding: '1.5rem' }}>
          <h3 style={{ margin: '0 0 0.5rem' }}>Rescues by Food Category</h3>
          <p style={{ fontSize: '0.875rem', color: 'var(--fl-text-muted)', marginBottom: '1.5rem' }}>
            Nutritional diversity delivered to partner recipient shelters.
          </p>
          <div style={{ height: '260px' }}>
            <ResponsiveContainer width="100%" height="100%">
              <BarChart data={categoryBreakdown}>
                <XAxis dataKey="category" stroke="var(--fl-text-muted)" fontSize={12} />
                <YAxis stroke="var(--fl-text-muted)" fontSize={12} />
                <Tooltip />
                <Bar dataKey="meals" name="Meals Delivered" fill="#1f8a5b" radius={[4, 4, 0, 0]} />
              </BarChart>
            </ResponsiveContainer>
          </div>
        </div>
      </div>

      {/* Impact Story Banner with High-Clarity Visual */}
      <div className="fl-card" style={{
        background: 'linear-gradient(135deg, var(--fl-teal-dark) 0%, var(--fl-teal) 100%)',
        color: '#fff',
        padding: '0',
        overflow: 'hidden',
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fit, minmax(320px, 1fr))',
        alignItems: 'stretch',
        borderRadius: 'var(--fl-radius-xl)',
        boxShadow: 'var(--fl-shadow-lg)'
      }}>
        <div style={{ padding: '2.5rem', display: 'flex', flexDirection: 'column', justifyContent: 'center' }}>
          <div>
            <span style={{ background: 'rgba(255,255,255,0.2)', padding: '4px 12px', borderRadius: '20px', fontSize: '0.75rem', fontWeight: 800, letterSpacing: '0.05em' }}>
              COMMUNITY IMPACT HIGHLIGHT
            </span>
            <h2 style={{ color: '#fff', margin: '1rem 0 0.75rem', fontSize: '1.65rem', lineHeight: 1.3 }}>
              "Over 120 children received fresh, wholesome dinner from hotel buffets this week."
            </h2>
            <p style={{ color: '#d8ece5', fontSize: '0.95rem', lineHeight: 1.6, margin: '0 0 1.25rem' }}>
              By automating time-critical matching before the 2-hour food safety window closes, FoodLoop guarantees that meals reach homes while still piping hot and safe.
            </p>
            <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
              <span style={{ fontSize: '1.5rem' }}>🍲</span>
              <div>
                <p style={{ margin: 0, fontWeight: 700, fontSize: '0.875rem' }}>Jinadasa Children's Home</p>
                <p style={{ margin: 0, color: 'rgba(255,255,255,0.7)', fontSize: '0.75rem' }}>Colombo 03 Partner Sanctuary</p>
              </div>
            </div>
          </div>
        </div>

        <div style={{ position: 'relative', minHeight: '260px' }}>
          <img
            src="/images/community-shelter.jpg"
            alt="Children receiving warm nutritious dinner at community shelter"
            style={{
              width: '100%',
              height: '100%',
              objectFit: 'cover',
              display: 'block'
            }}
          />
          <div style={{
            position: 'absolute',
            bottom: '12px',
            right: '12px',
            background: 'rgba(15, 23, 42, 0.75)',
            backdropFilter: 'blur(8px)',
            color: '#fff',
            padding: '6px 12px',
            borderRadius: '20px',
            fontSize: '11px',
            fontWeight: 600,
            display: 'flex',
            alignItems: 'center',
            gap: '6px'
          }}>
            <span>📍</span> Verified Community Delivery
          </div>
        </div>
      </div>
    </div>
  );
}